# Generated by Django 3.0.5 on 2020-04-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=7, unique=True, verbose_name='Ticker')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='Industry')),
                ('enterprise_value', models.FloatField(null=True, verbose_name='EV ($M)')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Time registered')),
                ('open_price', models.FloatField(verbose_name='Stock open price')),
                ('close_price', models.FloatField(verbose_name='Stock close price')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Company')),
            ],
        ),
    ]
